### ISSUE TITLE
Issue compiling iCub contrib 

### ISSUE THREAD

**Issue by KatePaulinne** [robotology/icub-contrib-common#6]
Hi,

I get the below error when trying to compile icub-contrib-common in CMake when following Windows installation guide. Could it be because I installed YARP (2.3.66) and iCub (1.4.0) from binaries rather than sources? I tried adding  the path to environment variable as the error suggests however it didn't work.. As you can see the below configures despite the error so I was able to generate project files but when I try to compile it in Visual Studio it errors as well.. 

Would anyone be able to help with this, please? I would be very grateful for suggestions.

```sh
Installation prefix is different from YARP: no file will we be installed into path.d folder, you need to set YARP_DATA_DIRS environment variable to C:\Program Files\robotology\yarp-2.3.66\share\yarp;C:\Program Files\robotology\icub-1.4.0\share\iCub;C:/Program Files/ICUBcontrib/share/ICUBcontrib;C:/Program Files/ICUBcontrib/share/ICUBcontrib
Configuring done
```

Thanks,
Kate

**Comment by pattacini** [comment]
Hi @KatePaulinne 

The env variable `YARP_DATA_DIRS` does not play any role while building and installing `icub-contrib-common`, since it serves merely to extend the collection of paths used by Yarp when searching for contexts at run-time.

I'd recommend you to make sure that Yarp is built/installed correctly (if you don't install it, ensure that `YARP_DIR` is defined properly) and to try reconfiguring the `icub-contrib-common` project from scratch, meaning by purging the CMake cache.

As of last resort, you may consider building Yarp from sources instead (you don't need iCub for these steps), although I tend to reckon it's quite unlikely that Yarp binaries could be the source of this problem.

**Comment by KatePaulinne** [comment]
Thanks for the reply, I managed to build and install it now, it seems the problem was that CMake didn't have write access on C drive.

**Comment by pattacini** [comment]
👍
